"""The generated-docs gate: docs/CONCEPTS.md must match fresh generator output.

The generator (scripts/gen_concept_index.py) is stdlib-only and parses source
with ast — it never imports forge — so it is loaded here by file path rather
than as a package module.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

V2_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = V2_ROOT / "scripts" / "gen_concept_index.py"
CONCEPTS = V2_ROOT / "docs" / "CONCEPTS.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_concept_index", SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_generator_covers_every_forge_module() -> None:
    gen = _load_generator()
    text = gen.generate()  # ast.parse failures anywhere in forge/ raise here
    for path in (V2_ROOT / "forge").rglob("*.py"):
        module = gen.module_name(path, V2_ROOT / "forge")
        assert f"### `{module}`" in text, f"missing module section: {module}"


def test_known_anchors_present() -> None:
    text = _load_generator().generate()
    assert "### `forge.kernel.step`" in text
    assert "- `step(state: SessionState, inp: Input, policy: Policy) -> Step`" in text
    assert "### `forge.ports.provider`" in text
    assert "`class Provider(Protocol)`" in text
    assert "### `forge.drive.session`" in text
    assert "`class SessionHandle`" in text


def test_header_and_regenerate_command() -> None:
    lines = _load_generator().generate().splitlines()
    assert lines[0] == "<!-- generated by scripts/gen_concept_index.py — do not edit -->"
    assert lines[1] == "<!-- regenerate: uv run python scripts/gen_concept_index.py -->"


def test_output_is_deterministic() -> None:
    gen = _load_generator()
    assert gen.generate() == gen.generate()


def test_committed_concepts_md_is_byte_identical(tmp_path: Path) -> None:
    """The drift gate that replaces hand-maintained docs."""
    out = tmp_path / "CONCEPTS.md"
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--out", str(out)],
        capture_output=True,
        text=True,
        cwd=V2_ROOT,
    )
    assert proc.returncode == 0, proc.stderr
    assert CONCEPTS.exists(), "docs/CONCEPTS.md not committed; run the generator"
    assert CONCEPTS.read_bytes() == out.read_bytes(), (
        "docs/CONCEPTS.md is stale; regenerate: uv run python scripts/gen_concept_index.py"
    )


def test_check_mode_passes_on_fresh_output() -> None:
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        capture_output=True,
        text=True,
        cwd=V2_ROOT,
    )
    assert proc.returncode == 0, proc.stderr
