#!/usr/bin/env python3
"""Generate docs/CONCEPTS.md — a one-line-per-symbol index of the forge package.

Stdlib-only on purpose: modules are parsed with ast, never imported, so the
generator runs without forge's dependencies installed. Output is deterministic
(modules and symbols sorted within each layer group) so regeneration is
diff-stable; tests/test_concept_index.py gates drift by byte-comparing the
committed file against fresh output.

Usage:
    uv run python scripts/gen_concept_index.py            # rewrite docs/CONCEPTS.md
    uv run python scripts/gen_concept_index.py --check    # exit 1 if stale
    uv run python scripts/gen_concept_index.py --out PATH # write elsewhere
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

V2_ROOT = Path(__file__).resolve().parent.parent
FORGE = V2_ROOT / "forge"
DEFAULT_OUT = V2_ROOT / "docs" / "CONCEPTS.md"

HEADER = "<!-- generated by scripts/gen_concept_index.py — do not edit -->"
REGEN = "<!-- regenerate: uv run python scripts/gen_concept_index.py -->"

# Dependency order; "forge" is the root package overview. Unknown layers (a
# future package this script hasn't been told about) sort after, alphabetically.
LAYER_ORDER = ("forge", "kernel", "ports", "policy", "drive", "adapters", "testing", "front")


def module_name(path: Path, pkg_root: Path) -> str:
    parts = list(path.relative_to(pkg_root.parent).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def layer_of(module: str) -> str:
    parts = module.split(".")
    return parts[1] if len(parts) > 1 else parts[0]


def first_doc_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node)
    return doc.strip().splitlines()[0].strip() if doc else ""


def _format_arg(arg: ast.arg, default: ast.expr | None) -> str:
    text = arg.arg
    if arg.annotation is not None:
        text += f": {ast.unparse(arg.annotation)}"
        if default is not None:
            text += f" = {ast.unparse(default)}"
    elif default is not None:
        text += f"={ast.unparse(default)}"
    return text


def format_function(fn: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    a = fn.args
    positional = a.posonlyargs + a.args
    defaults: list[ast.expr | None] = [None] * (len(positional) - len(a.defaults))
    defaults += list(a.defaults)
    parts: list[str] = []
    for i, (arg, default) in enumerate(zip(positional, defaults)):
        parts.append(_format_arg(arg, default))
        if a.posonlyargs and i == len(a.posonlyargs) - 1:
            parts.append("/")
    if a.vararg is not None:
        parts.append("*" + _format_arg(a.vararg, None))
    elif a.kwonlyargs:
        parts.append("*")
    parts += [_format_arg(arg, d) for arg, d in zip(a.kwonlyargs, a.kw_defaults)]
    if a.kwarg is not None:
        parts.append("**" + _format_arg(a.kwarg, None))
    sig = f"{fn.name}({', '.join(parts)})"
    if fn.returns is not None:
        sig += f" -> {ast.unparse(fn.returns)}"
    if isinstance(fn, ast.AsyncFunctionDef):
        sig = "async " + sig
    return sig


def is_dataclass(cls: ast.ClassDef) -> bool:
    for dec in cls.decorator_list:
        target = dec.func if isinstance(dec, ast.Call) else dec
        name = target.attr if isinstance(target, ast.Attribute) else getattr(target, "id", "")
        if name == "dataclass":
            return True
    return False


def dataclass_fields(cls: ast.ClassDef) -> list[str]:
    fields: list[str] = []
    for stmt in cls.body:
        if not (isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)):
            continue
        if stmt.target.id.startswith("_"):
            continue
        annotation = ast.unparse(stmt.annotation)
        if annotation.startswith("ClassVar"):  # not an init field
            continue
        field = f"{stmt.target.id}: {annotation}"
        if stmt.value is not None:
            field += f" = {ast.unparse(stmt.value)}"
        fields.append(field)
    return fields


def format_class(cls: ast.ClassDef) -> str:
    if is_dataclass(cls):
        sig = f"@dataclass {cls.name}({', '.join(dataclass_fields(cls))})"
    elif cls.bases:
        sig = f"class {cls.name}({', '.join(ast.unparse(b) for b in cls.bases)})"
    else:
        sig = f"class {cls.name}"
    line = f"`{sig}`"
    doc = first_doc_line(cls)
    if doc:
        line += f" — {doc}"
    methods = sorted(
        {
            stmt.name
            for stmt in cls.body
            if isinstance(stmt, ast.FunctionDef | ast.AsyncFunctionDef)
            and not stmt.name.startswith("_")
        }
    )
    if methods:
        line += f" (methods: {', '.join(methods)})"
    return line


def symbol_lines(tree: ast.Module) -> list[str]:
    lines: dict[str, str] = {}  # name -> line, first definition wins (overloads)
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            lines.setdefault(node.name, format_class(node))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and not node.name.startswith("_"):
            line = f"`{format_function(node)}`"
            doc = first_doc_line(node)
            if doc:
                line += f" — {doc}"
            lines.setdefault(node.name, line)
    return [lines[name] for name in sorted(lines)]


def module_section(path: Path, pkg_root: Path) -> tuple[str, str, list[str]]:
    """Returns (layer, module, markdown lines for this module)."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    module = module_name(path, pkg_root)
    heading = f"### `{module}`"
    doc = first_doc_line(tree)
    if doc:
        heading += f" — {doc}"
    lines = [heading]
    lines += [f"- {line}" for line in symbol_lines(tree)]
    return layer_of(module), module, lines


def generate(pkg_root: Path = FORGE) -> str:
    sections: dict[str, list[tuple[str, list[str]]]] = {}
    for path in sorted(pkg_root.rglob("*.py")):
        layer, module, lines = module_section(path, pkg_root)
        sections.setdefault(layer, []).append((module, lines))

    known = [layer for layer in LAYER_ORDER if layer in sections]
    extra = sorted(set(sections) - set(LAYER_ORDER))
    out = [HEADER, REGEN, "", "# forge v2 — concept index", ""]
    out.append("One line per public symbol, grouped by layer in dependency order.")
    for layer in known + extra:
        out += ["", f"## {layer}"]
        for _, lines in sorted(sections[layer]):
            out.append("")
            out += lines
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output path")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if --out is stale instead of writing"
    )
    args = parser.parse_args(argv)
    text = generate().encode("utf-8")
    if args.check:
        current = args.out.read_bytes() if args.out.exists() else b""
        if current != text:
            print(
                f"{args.out} is stale; regenerate: uv run python scripts/gen_concept_index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(text)  # bytes: keep \n endings stable across platforms
    return 0


if __name__ == "__main__":
    sys.exit(main())
